/**
 * Auto-generated API Client from OpenAPI specification
 * Generated from: mdJournal API v1.0.0
 * 
 * ⚠️ DO NOT EDIT MANUALLY - Generated by micro-contracts
 * @generated
 * 
 * Client API matches Service API signature (single input object).
 * Internally maps input to HTTP request (path params, query params, body).
 */

import type {
  CalendarServiceApi,
  ConfigServiceApi,
  GitServiceApi,
  ReportServiceApi,
} from '@mdjournal/contract/services/index.js';
import type {
  CalendarData,
  Calendar_getAvailableYearMonthsInput,
  Calendar_getCalendarDataInput,
  Calendar_getCalendarDataParams,
  Config,
  Config_getConfigInput,
  Config_getRoutinesMarkdownInput,
  Config_saveRoutinesMarkdownInput,
  Config_updateConfigInput,
  Error,
  ExtendedGitStatus,
  Git_getStatusInput,
  ProblemDetails,
  ReportResponse,
  ReportSaveRequest,
  ReportSaveResponse,
  Report_deleteReportInput,
  Report_deleteReportParams,
  Report_getReportInput,
  Report_getReportParams,
  Report_saveReportInput,
  Report_saveReportParams,
  RoutinesMarkdownRequest,
  RoutinesMarkdownResponse,
  YearMonthsResponse,
} from '@mdjournal/contract/schemas/types.js';

// BASE_URL derived from OpenAPI servers[0].url: /api
// Can be overridden via environment variable (Vite: VITE_API_URL)
const BASE_URL = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_URL) || '/api';

// ========================================
// API Error Class
// ========================================

export class ApiError extends Error {
  status: number;
  code?: string;
  
  constructor(status: number, message: string, code?: string) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.code = code;
  }
}

// ========================================
// Fetch Helper
// ========================================

async function handleResponse<T>(res: Response): Promise<T> {
  if (!res.ok) {
    const errorBody = await res.json().catch(() => ({ message: 'API Error' }));
    throw new ApiError(
      res.status,
      errorBody.message || `HTTP ${res.status}`,
      errorBody.code
    );
  }
  // Handle 204 No Content and empty responses
  if (res.status === 204 || res.headers.get('content-length') === '0') {
    return undefined as T;
  }
  return res.json();
}

// ========================================
// API Clients (Service-aligned)
// ========================================

/**
 * Calendar API Client
 */
export const calendarApi: CalendarServiceApi = {
  /**
   * GET /calendar
   * カレンダー用集計データ取得
   */
  async getCalendarData(input: Calendar_getCalendarDataInput): Promise<CalendarData> {
    const searchParams = new URLSearchParams();
    if (input.year !== undefined) searchParams.set('year', String(input.year));
    if (input.month !== undefined) searchParams.set('month', String(input.month));
    const url = `${BASE_URL}/calendar` + (searchParams.toString() ? '?' + searchParams : '');
    const res = await fetch(url);
    return handleResponse<CalendarData>(res);
  },

  /**
   * GET /calendar/months
   * 日報が存在する年月リスト取得
   */
  async getAvailableYearMonths(_input: Calendar_getAvailableYearMonthsInput): Promise<YearMonthsResponse> {
    const url = `${BASE_URL}/calendar/months`;
    const res = await fetch(url);
    return handleResponse<YearMonthsResponse>(res);
  },

};

/**
 * Config API Client
 */
export const configApi: ConfigServiceApi = {
  /**
   * GET /config
   * 設定取得
   */
  async getConfig(_input: Config_getConfigInput): Promise<Config> {
    const url = `${BASE_URL}/config`;
    const res = await fetch(url);
    return handleResponse<Config>(res);
  },

  /**
   * PUT /config
   * 設定更新
   */
  async updateConfig(input: Config_updateConfigInput): Promise<Config> {
    const url = `${BASE_URL}/config`;
    const res = await fetch(url, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(input.data),
    });
    return handleResponse<Config>(res);
  },

  /**
   * GET /config/routines/markdown
   * ルーチン設定をMarkdown形式で取得
   */
  async getRoutinesMarkdown(_input: Config_getRoutinesMarkdownInput): Promise<RoutinesMarkdownResponse> {
    const url = `${BASE_URL}/config/routines/markdown`;
    const res = await fetch(url);
    return handleResponse<RoutinesMarkdownResponse>(res);
  },

  /**
   * PUT /config/routines/markdown
   * ルーチン設定をMarkdown形式で保存
   */
  async saveRoutinesMarkdown(input: Config_saveRoutinesMarkdownInput): Promise<RoutinesMarkdownResponse> {
    const url = `${BASE_URL}/config/routines/markdown`;
    const res = await fetch(url, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(input.data),
    });
    return handleResponse<RoutinesMarkdownResponse>(res);
  },

};

/**
 * Git API Client
 */
export const gitApi: GitServiceApi = {
  /**
   * GET /git/status
   * Git状態取得
   */
  async getStatus(_input: Git_getStatusInput): Promise<ExtendedGitStatus> {
    const url = `${BASE_URL}/git/status`;
    const res = await fetch(url);
    return handleResponse<ExtendedGitStatus>(res);
  },

};

/**
 * Report API Client
 */
export const reportApi: ReportServiceApi = {
  /**
   * GET /reports/{date}
   * 日報取得
   */
  async getReport(input: Report_getReportInput): Promise<ReportResponse> {
    const url = `${BASE_URL}/reports/${input.date}`;
    const res = await fetch(url);
    return handleResponse<ReportResponse>(res);
  },

  /**
   * PUT /reports/{date}
   * 日報保存
   */
  async saveReport(input: Report_saveReportInput): Promise<ReportSaveResponse> {
    const url = `${BASE_URL}/reports/${input.date}`;
    const res = await fetch(url, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(input.data),
    });
    return handleResponse<ReportSaveResponse>(res);
  },

  /**
   * DELETE /reports/{date}
   * 日報削除
   */
  async deleteReport(input: Report_deleteReportInput): Promise<void> {
    const url = `${BASE_URL}/reports/${input.date}`;
    const res = await fetch(url, { method: 'DELETE' });
    await handleResponse<void>(res);
  },

};


// ========================================
// Re-export types for convenience
// ========================================

export type {
  CalendarData,
  Calendar_getAvailableYearMonthsInput,
  Calendar_getCalendarDataInput,
  Calendar_getCalendarDataParams,
  Config,
  Config_getConfigInput,
  Config_getRoutinesMarkdownInput,
  Config_saveRoutinesMarkdownInput,
  Config_updateConfigInput,
  Error,
  ExtendedGitStatus,
  Git_getStatusInput,
  ProblemDetails,
  ReportResponse,
  ReportSaveRequest,
  ReportSaveResponse,
  Report_deleteReportInput,
  Report_deleteReportParams,
  Report_getReportInput,
  Report_getReportParams,
  Report_saveReportInput,
  Report_saveReportParams,
  RoutinesMarkdownRequest,
  RoutinesMarkdownResponse,
  YearMonthsResponse,
};
